/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.cdc_demo.data_faker.avro_generated;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Product item */
@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 764662939862193001L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"org.cdc_demo.data_faker.avro_generated\",\"doc\":\"Product item\",\"fields\":[{\"name\":\"product_name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of product\"},{\"name\":\"product_description\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Description of product\"},{\"name\":\"list_price\",\"type\":\"float\",\"doc\":\"Product price\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<Product>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Product>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of product */
   private java.lang.String product_name;
  /** Description of product */
   private java.lang.String product_description;
  /** Product price */
   private float list_price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Product() {}

  /**
   * All-args constructor.
   * @param product_name Name of product
   * @param product_description Description of product
   * @param list_price Product price
   */
  public Product(java.lang.String product_name, java.lang.String product_description, java.lang.Float list_price) {
    this.product_name = product_name;
    this.product_description = product_description;
    this.list_price = list_price;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return product_name;
    case 1: return product_description;
    case 2: return list_price;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: product_name = value$ != null ? value$.toString() : null; break;
    case 1: product_description = value$ != null ? value$.toString() : null; break;
    case 2: list_price = (java.lang.Float)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'product_name' field.
   * @return Name of product
   */
  public java.lang.String getProductName() {
    return product_name;
  }


  /**
   * Sets the value of the 'product_name' field.
   * Name of product
   * @param value the value to set.
   */
  public void setProductName(java.lang.String value) {
    this.product_name = value;
  }

  /**
   * Gets the value of the 'product_description' field.
   * @return Description of product
   */
  public java.lang.String getProductDescription() {
    return product_description;
  }


  /**
   * Sets the value of the 'product_description' field.
   * Description of product
   * @param value the value to set.
   */
  public void setProductDescription(java.lang.String value) {
    this.product_description = value;
  }

  /**
   * Gets the value of the 'list_price' field.
   * @return Product price
   */
  public float getListPrice() {
    return list_price;
  }


  /**
   * Sets the value of the 'list_price' field.
   * Product price
   * @param value the value to set.
   */
  public void setListPrice(float value) {
    this.list_price = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   * @return A new Product RecordBuilder
   */
  public static org.cdc_demo.data_faker.avro_generated.Product.Builder newBuilder() {
    return new org.cdc_demo.data_faker.avro_generated.Product.Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static org.cdc_demo.data_faker.avro_generated.Product.Builder newBuilder(org.cdc_demo.data_faker.avro_generated.Product.Builder other) {
    if (other == null) {
      return new org.cdc_demo.data_faker.avro_generated.Product.Builder();
    } else {
      return new org.cdc_demo.data_faker.avro_generated.Product.Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static org.cdc_demo.data_faker.avro_generated.Product.Builder newBuilder(org.cdc_demo.data_faker.avro_generated.Product other) {
    if (other == null) {
      return new org.cdc_demo.data_faker.avro_generated.Product.Builder();
    } else {
      return new org.cdc_demo.data_faker.avro_generated.Product.Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
    implements org.apache.avro.data.RecordBuilder<Product> {

    /** Name of product */
    private java.lang.String product_name;
    /** Description of product */
    private java.lang.String product_description;
    /** Product price */
    private float list_price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.cdc_demo.data_faker.avro_generated.Product.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.product_name)) {
        this.product_name = data().deepCopy(fields()[0].schema(), other.product_name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.product_description)) {
        this.product_description = data().deepCopy(fields()[1].schema(), other.product_description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.list_price)) {
        this.list_price = data().deepCopy(fields()[2].schema(), other.list_price);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     * @param other The existing instance to copy.
     */
    private Builder(org.cdc_demo.data_faker.avro_generated.Product other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.product_name)) {
        this.product_name = data().deepCopy(fields()[0].schema(), other.product_name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.product_description)) {
        this.product_description = data().deepCopy(fields()[1].schema(), other.product_description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.list_price)) {
        this.list_price = data().deepCopy(fields()[2].schema(), other.list_price);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'product_name' field.
      * Name of product
      * @return The value.
      */
    public java.lang.String getProductName() {
      return product_name;
    }


    /**
      * Sets the value of the 'product_name' field.
      * Name of product
      * @param value The value of 'product_name'.
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder setProductName(java.lang.String value) {
      validate(fields()[0], value);
      this.product_name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'product_name' field has been set.
      * Name of product
      * @return True if the 'product_name' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'product_name' field.
      * Name of product
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder clearProductName() {
      product_name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_description' field.
      * Description of product
      * @return The value.
      */
    public java.lang.String getProductDescription() {
      return product_description;
    }


    /**
      * Sets the value of the 'product_description' field.
      * Description of product
      * @param value The value of 'product_description'.
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder setProductDescription(java.lang.String value) {
      validate(fields()[1], value);
      this.product_description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'product_description' field has been set.
      * Description of product
      * @return True if the 'product_description' field has been set, false otherwise.
      */
    public boolean hasProductDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'product_description' field.
      * Description of product
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder clearProductDescription() {
      product_description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'list_price' field.
      * Product price
      * @return The value.
      */
    public float getListPrice() {
      return list_price;
    }


    /**
      * Sets the value of the 'list_price' field.
      * Product price
      * @param value The value of 'list_price'.
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder setListPrice(float value) {
      validate(fields()[2], value);
      this.list_price = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'list_price' field has been set.
      * Product price
      * @return True if the 'list_price' field has been set, false otherwise.
      */
    public boolean hasListPrice() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'list_price' field.
      * Product price
      * @return This builder.
      */
    public org.cdc_demo.data_faker.avro_generated.Product.Builder clearListPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        Product record = new Product();
        record.product_name = fieldSetFlags()[0] ? this.product_name : (java.lang.String) defaultValue(fields()[0]);
        record.product_description = fieldSetFlags()[1] ? this.product_description : (java.lang.String) defaultValue(fields()[1]);
        record.list_price = fieldSetFlags()[2] ? this.list_price : (java.lang.Float) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product>
    WRITER$ = (org.apache.avro.io.DatumWriter<Product>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product>
    READER$ = (org.apache.avro.io.DatumReader<Product>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.product_name);

    out.writeString(this.product_description);

    out.writeFloat(this.list_price);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.product_name = in.readString();

      this.product_description = in.readString();

      this.list_price = in.readFloat();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.product_name = in.readString();
          break;

        case 1:
          this.product_description = in.readString();
          break;

        case 2:
          this.list_price = in.readFloat();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










